# vim: ft=yaml ts=2:
---

- debug: var=apache
  tags:
    - never
    - debug

- name: set OS specific variables
  include_vars:
    file: "{{ ansible_os_family }}.yml"

- debug: var=apache
  tags:
    - never
    - debug
...
