# vim: ft=yaml ts=2:
---

- name: debug before OS specific variables
  debug: var=apache
  tags:
    - never
    - debug

- name: set OS specific variables
  include_vars:
    file: "{{ ansible_os_family }}.yml"

- name: debug after OS specific variables
  debug: var=apache
  tags:
    - never
    - debug

- debug: var=_apache_scl_tmpvar
  tags:
    - never
    - debug
...
