# vim: set ts=2:

ENV container docker

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*; \
rm -f /lib/systemd/system/anaconda.target.wants/*;

RUN  yum -y install epel-release \
&& yum install -y python-setuptools python-pip systemd \
&& rm -rf /var/cache/yum/*

RUN pip install wheel && pip install ansible && pip install ansible-lint

RUN  mkdir -p /etc/ansible\
&& echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

RUN  yum -y install epel-release \
  && yum install -y python-setuptools python-pip systemd \
  && rm -rf /var/cache/yum/*

RUN pip install wheel \
&& pip install ansible \
&& pip install ansible-lint \
&& rm -fr /root/.cache/pip/

RUN mkdir -p /etc/ansible && echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/sbin/init"]
