---

- name: restart apache
  when: apache.service.managed
  service:
    name: "{{ apache.service }}"
    state: restarted

- name: reload apache
  service:
    name: "{{ apache.service }}"
    state: reloaded
