---

- name: restart apache
  service:
    name: "{{ apache.service }}"
    state: restarted

- name: reload apache
  service:
    name: "{{ apache.service }}"
    state: reloaded
  listen:
    - check for changed key
    - check for changed cert
    - check for changed chain

- name: symlink into /etc/profile.d
  when:
    - apache.scl.name is defined
    - apache.scl.enabled is defined
  file:
    src: /opt/{{ apache.scl.prefix }}/{{ apache.scl.name }}/enable
    dest: /etc/profile.d/{{ apache.scl.name }}.sh
    state: link

