# vim: set ft=yaml ts=2:
---

- name: debug apache
  debug: var=apache
  tags:
    - never
    - debug

- name: httpd does exist
  package:
    name: "{{ apache.package }}"
    state: installed

- name: apache is running
  service:
    name: "{{ apache.service }}"
    state: started
    enabled: true

- name: include scl specific tasks
  when: apache.scl.name
  include_tasks:
    file: scl.yml
